title = "Jason Gabunilas"
# baseURL = "https://jgabunilas.github.io/portfolio/"
baseURL = "https://jgabunilas.onrender.com/"

languageCode = "en-us"
theme = "ananke"
# resourceDir = "../resources"

DefaultContentLanguage = "en"
# The SectionPagesMenu option must be disabled in order to use custom menu definitions. See below.
# SectionPagesMenu = "main"
# [pagination]
# pagerSize = 6 # determines how many projects are displayed per page
Paginate = 6 # determines how many projects are displayed per page
# googleAnalytics = ""
enableRobotsTXT = true
# canonifyURLs = true
# relativeURLs = true

[languages]
  [languages.en]
    title = "Jason Gabunilas"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  # [languages.fr]
  #   title = "Ananke Fr"
  #   weight = 2
  #   contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


# Custom menu definition with weighted page links
[menus]
[[menus.main]]
    name = 'About Me'
    pageRef = '/about'
    weight = 10
[[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    weight = 20
[[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 30



[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3 # determines how many projects are displayed on the main page
  linkedin = "https://www.linkedin.com/in/jason-gabunilas/"
  github = "https://github.com/jgabunilas"

# [[module.mounts]]
# source = 'static'
# target = 'static'

# [[module.mounts]]
# source = 'images'
# target = 'static/images'

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"